# Generated by Django 4.0.3 on 2022-05-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
